### ISSUE TITLE
Axis tick labels do not work with integer float locations

### ISSUE THREAD

**Issue by SvenWarnke** [pyviz/holoviews#3583]
If ticks are set with location and label, label is not used if location is a float that could be converted to integer. 
Example:
`import holoviews as hv`
`hv.extension('bokeh')`
`hv.Curve([(1, 2), (2, 2)]).options(yticks=[(1.3434, 'hi'), (2., 'ho')])`
yields 
![image](https://user-images.githubusercontent.com/44029716/55087235-121c0780-50aa-11e9-8e79-82a6a1f1ed6e.png)

whereas it is correctly displayed for integer position:
`hv.Curve([(1, 2), (2, 2)]).options(yticks=[(1.3434, 'hi'), (2, 'ho')])`
![image](https://user-images.githubusercontent.com/44029716/55087356-4394d300-50aa-11e9-9575-7c45c1c11814.png)

The same holds for xticks.

I have holoviews 1.11.3

**Comment by philippjfr** [comment]
That's bizarre, thanks for reporting this. I'm guessing this is an upstream issue in bokeh but will have to confirm.

**Comment by philippjfr** [comment]
Yeah, pretty sure this is a bokeh issue, specifically because the ticks are specified as a dictionary, and in JS objects can only have string keys. Since the string representation of 2.0 in JS is "2" the lookup fails, because in Python the representation is "2.0".

**Comment by philippjfr** [comment]
I'll work around this by casting floats that are ints to integers, but this should probably be fixed in bokeh as well.

**Comment by Sieboldianus** [comment]
Ah, @philippjfr this is super strange. Apparently, the fix works for the examples above:

![image](https://user-images.githubusercontent.com/13646666/130436208-d9b0501f-bc3b-47ce-9d29-9013af72f429.png)

.. but does not for (e.g.) `10.0`.

![image](https://user-images.githubusercontent.com/13646666/130436247-aca6e05f-b2a9-4c1c-a01e-e8fa0fb44340.png)

**Comment by Sieboldianus** [comment]
@philippjfr

The same problem still exists in Holoviews, when overriding cmap-tick locations. E.g.:

```python
cmap = plt.cm.get_cmap("OrRd", 6)
ticks = [1, 2, 3, 4.5, 5.0, 6, 7]]
color_levels =  len(cmap.colors)
image_layer = img_grid.opts(
            color_levels=color_levels,
            cmap=cmap,
            colorbar=True,
            clipping_colors={'NaN': 'transparent'},
            colorbar_opts={
                'major_label_text_align':'left',
                'major_label_overrides': label_dict,
                'ticker': FixedTicker(
                    ticks=ticks),
                })
```

All of the above ticks get plotted, except `5.0`.

But I think this is more or less an issue with Bokeh, not Holoviews, correct?

**Comment by MarcSkovMadsen** [comment]
Hi @Sieboldianus . Thanks for reporting. Please open a new issue. This one has been closed.

**Comment by Sieboldianus** [comment]
Yes, thank you. Already working on a minimum, reproducible example. Apologies for that.

**Comment by MarcSkovMadsen** [comment]
No problem. I'm just nudging here so that we can get the Philipp and his gang can focus their energy on fixing the issue instead of understanding, reproducing, making test examples etc. :-)

And again thanks for taking the time to contribute to making HoloViz better for all of us 👍
